.TH NFO-MODIFIER 1 "April 18, 2014"
.SH NAME
nfo-modifier \- view, edit and generate nfo files
.SH SYNOPSIS
.B nfo-modifier
[\fIOPTION...\fR]

.SH DESCRIPTION
.PP
nfo-modifier is a Java application that allows the modification of .nfo files
(i.e. encoded in cp437 ) and provides several tools to ease the creation and
manipulation of nfo.

.PP

Options:

  --file,-f [file]

  Open the specified [file] and display it.


  --create-data, -cd [file]

  Create a new empty profile data file named [file].


  --load-data, -ld [file]

  Load the profile data file named [file].

  --profile,-p [option]

  Choose the profile to use, requires
.B --load-data
option.

  --create-profile,-cp [option1..5]

  Create a new profile, the first option is the name, followed by 4 files in the following order: header, body, border and footer. Needs to use
.B --load-data
before.

  --delete-profile [option]

  Delete a profile matching [option] name. Need to use
.B --load-data
before.

  --list-profiles,-ls

  List all the profile names store. Need to use
.B --load-data
before.

  --output-log [file]

  Specify a [file] to store displayed messages, if not specified the default output is used. For a file to store cp437 data see
.B --output-file

  --output-file,-o [file]

  Specify a [file] to store cp437 displayed data, if not specified the default output is used with default (readable) encoding.

  --no-gui, -ng

  Do not create the Graphical User Interface.

  --silent

  Turn off messages AND nfo output, you may need
.B --output-log
and
.B --output-file
.

.SH EXAMPLES

.B nfo-modifier
--create-data
.I profile.data

Create a new empty profile data file named profile.data

.B nfo-modifier
--load-data
.I profile.data
--create-profile MyProfile
.I header.txt border.txt body.txt footer.txt

Create a new profile named MyProfile into the file profile.data from the given text files.

.B nfo-modifier
--load-data profile.data -ls

Display a list of all the profiles from the file
.I profile.data
.

.B nfo-modifier
-ld
.I profile.data
--profile MyProfile --content
.I content.txt
--output-file
.I myCoolNFO.nfo

Use the profile
.I MyProfile
from the profile data file
.I profile.data
and the raw content
.I content.txt
to create the nfo file
.I myCoolNFO.nfo


.SH BUGS

To report a bug, please visit https://github.com/AlexandreRio/nfo-modifier

.SH AUTHOR
Written by Alexandre Rio <contact@alexrio.fr>.
